ORG 00H 
MOV P1, #0H		;SETTING PORT 1 AS OUTPUT PORT

AGAIN:	SETB P1.7	;GIVING HIGH PULSE
	ACALL DELAY 	;DELAY FOR 5ms
	CLR P1.7 	;GIVING LOW PULSE
	ACALL DELAY 	;DELAY FOR 5ms
	ACALL DELAY 	;DELAY FOR 5ms
	SJMP AGAIN 	;KEEP DOING THIS 

ORG 300H 
DELAY:	MOV R2, #36
L2:	MOV R1, #255
L1: 	DJNZ R1, L1	;AS CALCULATED, THE LOOP WILL RUN FOR 36*255=9180 TIMES
	DJNZ R2, L2

	RET

END
	


