ORG 00H

MOV P1, #0		;TO TURN ON BUZZER & LED AS OUTPUT
MOV P0, #220		;TO TAKE TEMPERATURE AS INPUT, LET TEMP=220F

BUZZER EQU P1.7		;BUZZER IS CONNECTED IN THE PIN 7 OF PORT 1
RED_LED EQU P1.6	;RED LED IS CONNECTED IN THE PIN 6 OF PORT 1


AGAIN: 	MOV A, P0
	CJNE A, #210, NEXT
	SJMP NOPE
	
NEXT:	JNC YEAH
	JC NOPE

YEAH:	SETB BUZZER
	SETB RED_LED
	SJMP AGAIN

NOPE: 	CLR BUZZER
	SETB RED_LED
	SJMP AGAIN

END


